<?php
define('NOVELLITE_MONTHLY_ARCHIVES', 'Try looking in the monthly archives. %1$s');
define('SORRY_NO_POST_MATCHED', 'Sorry, no posts matched your criteria.');
define('BLOG_ARCHIVES', 'Blog Archives');
define('CATEGORY_ARCHIVES', 'Category Archives: %s');
define('PAGE', 'Page %s');
define('SEARCH_RESULT', 'Search Results for: %s');
define('TAG_ARCHIVES', 'Tag Archives: %s');
define('DAILY_ARCHIVES', 'Daily Archives: %s');
define('LCN_MAP', 'Location Map');
define('YEARLY_ARCHIVES', 'Yearly Archives: %s');
define('AUTHOR_ARCHIVES', 'Author Archives: %s');
define('ABOUT', 'About: %s');
define('HOME_TEXT', 'Home');
define('THIS_ENTRY_WAS_POSTED_IN', 'This entry was posted in %1$s');
define('PERMALINK', 'permalink');
define('BOOKMARK_THE', 'Bookmark the');
define('PRIMARY_WIDGET', 'Primary Widget Area');
define('THE_PRIMARY_WIDGET', 'The primary widget area');
define('SECONDRY_WIDGET', 'Secondary Widget Area');
define('THE_SECONDRY_WIDGET', 'The secondary widget area');
define('SMT_CMT', 'Submit Comment');
define('LV_CMT', 'Leave a Comment');
define('OLDER_POSTS', '&larr; Older posts');
define('NEWER_POSTS', 'Newer posts &rarr;');
define('PREV_POST', 'Previous Post');
define('NEXT_POST', 'Next Post');
define('READ_MORE', 'Read More');
define('SND_MSG', 'Send Your Message');
define('RETURN_TO', 'Return to %s');
define('BY_AUTHOR', 'By %2$s');
define('VIEW_ALL_POST_BY', 'View all posts by %s');
define('PUBLISHED_BY', 'Published %2$s');
define('FULL_SIZE_IS_PIXEL', 'Full size is %s pixels');
define('LINK_TO_FULL_SIZE_IMAGE', 'Link to full-size image');
define('EDIT_TEXT', 'Edit');
define('CONTINUE_READING', 'Continue reading →');
define('PAGES_COLON', 'Pages:');
define('CONTINUE_READING_DOTS', 'Continue Reading');
define('POSTED_BY', 'Posted by');
define('AND_TAGGED', 'and tagged');
define('SMT_MSG', 'Submit Message');
define('CONTACT_NAME', 'Your Name');
define('CONTACT_EMAIL', 'Your Email');
define('CONTACT_MESSAGE', 'Your Message');
define('FORM_SEARCH', 'Search');
define('CMNT_CLSD', 'Comments are closed.');
define('NO_CMNT', 'No Comments');
define('ONE_CMNT', 'One Comments');
define('CMNT', 'Comments');
define('POST_TAGGED_WITH', 'Post Tag With :');
define('CONTACT_SUBJECT', 'Subject');
define('CONTACT_SUBMIT', 'Submit Message');
define('TESTIMONIAL_BG_IMAGE',get_template_directory_uri().'/images/testimonial-back.jpg');
define('PRICING_BG_IMAGE',get_template_directory_uri().'/images/pricing.jpg');
define('CONTACT_BG_IMAGE',get_template_directory_uri().'/images/contact-back.jpg');

?>